- block:
  - name: Install nginx 
    apt: name={{ item }} state=present
    with_items:
      - nginx

  - name: Install web role specific dependencies
    apt: name={{ item }} state=installed
    with_items:
        - git    

  - name : Creates directory
     
    file : 
      path:  "{{ item }}"
      owner: pi
      group: pi
      state: directory
      mode: 754

    with_items:
      - /opt/bb/bin
      - /opt/bb/logs
      - /var/log/nginx
      - /opt/bb/var/run

  become: yes
  become_method: sudo    